# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import FoodBotSim_pb2 as FoodBotSim__pb2


class FoodBotSimRequestStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSimResponse = channel.unary_unary(
        '/FoodBot.FoodBotSimRequest/GetSimResponse',
        request_serializer=FoodBotSim__pb2.Sentence.SerializeToString,
        response_deserializer=FoodBotSim__pb2.Sentence.FromString,
        )


class FoodBotSimRequestServicer(object):

  def GetSimResponse(self, request, context):
    """Input NLG
    Output NLG 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FoodBotSimRequestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSimResponse': grpc.unary_unary_rpc_method_handler(
          servicer.GetSimResponse,
          request_deserializer=FoodBotSim__pb2.Sentence.FromString,
          response_serializer=FoodBotSim__pb2.Sentence.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FoodBot.FoodBotSimRequest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
