# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FoodBot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FoodBot.proto',
  package='FoodBot',
  syntax='proto3',
  serialized_pb=_b('\n\rFoodBot.proto\x12\x07\x46oodBot\"^\n\x08Sentence\x12\x16\n\x0esemantic_frame\x18\x01 \x01(\t\x12\x14\n\x0cnlg_sentence\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x13\n\x0bgood_policy\x18\x04 \x01(\x05\"O\n\x0boutSentence\x12\x14\n\x0cresponse_nlg\x18\x05 \x01(\t\x12\x1d\n\x15response_policy_frame\x18\x06 \x01(\t\x12\x0b\n\x03url\x18\x07 \x01(\t2J\n\x0e\x46oodBotRequest\x12\x38\n\x0bGetResponse\x12\x11.FoodBot.Sentence\x1a\x14.FoodBot.outSentence\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='FoodBot.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='semantic_frame', full_name='FoodBot.Sentence.semantic_frame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nlg_sentence', full_name='FoodBot.Sentence.nlg_sentence', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='FoodBot.Sentence.user_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='good_policy', full_name='FoodBot.Sentence.good_policy', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=120,
)


_OUTSENTENCE = _descriptor.Descriptor(
  name='outSentence',
  full_name='FoodBot.outSentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_nlg', full_name='FoodBot.outSentence.response_nlg', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_policy_frame', full_name='FoodBot.outSentence.response_policy_frame', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='FoodBot.outSentence.url', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['outSentence'] = _OUTSENTENCE

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'FoodBot_pb2'
  # @@protoc_insertion_point(class_scope:FoodBot.Sentence)
  ))
_sym_db.RegisterMessage(Sentence)

outSentence = _reflection.GeneratedProtocolMessageType('outSentence', (_message.Message,), dict(
  DESCRIPTOR = _OUTSENTENCE,
  __module__ = 'FoodBot_pb2'
  # @@protoc_insertion_point(class_scope:FoodBot.outSentence)
  ))
_sym_db.RegisterMessage(outSentence)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class FoodBotRequestStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetResponse = channel.unary_unary(
          '/FoodBot.FoodBotRequest/GetResponse',
          request_serializer=Sentence.SerializeToString,
          response_deserializer=outSentence.FromString,
          )


  class FoodBotRequestServicer(object):

    def GetResponse(self, request, context):
      """Input NLG
      Output NLG 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_FoodBotRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetResponse': grpc.unary_unary_rpc_method_handler(
            servicer.GetResponse,
            request_deserializer=Sentence.FromString,
            response_serializer=outSentence.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'FoodBot.FoodBotRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaFoodBotRequestServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetResponse(self, request, context):
      """Input NLG
      Output NLG 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaFoodBotRequestStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetResponse(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Input NLG
      Output NLG 
      """
      raise NotImplementedError()
    GetResponse.future = None


  def beta_create_FoodBotRequest_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('FoodBot.FoodBotRequest', 'GetResponse'): Sentence.FromString,
    }
    response_serializers = {
      ('FoodBot.FoodBotRequest', 'GetResponse'): outSentence.SerializeToString,
    }
    method_implementations = {
      ('FoodBot.FoodBotRequest', 'GetResponse'): face_utilities.unary_unary_inline(servicer.GetResponse),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_FoodBotRequest_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('FoodBot.FoodBotRequest', 'GetResponse'): Sentence.SerializeToString,
    }
    response_deserializers = {
      ('FoodBot.FoodBotRequest', 'GetResponse'): outSentence.FromString,
    }
    cardinalities = {
      'GetResponse': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'FoodBot.FoodBotRequest', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
