# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import FoodBotRLAgent_pb2 as FoodBotRLAgent__pb2


class FoodBotRLRequestStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRLResponse = channel.unary_unary(
        '/FoodBot.FoodBotRLRequest/GetRLResponse',
        request_serializer=FoodBotRLAgent__pb2.EnvornmentInfomration.SerializeToString,
        response_deserializer=FoodBotRLAgent__pb2.Policy.FromString,
        )


class FoodBotRLRequestServicer(object):

  def GetRLResponse(self, request, context):
    """Input NLG
    Output NLG 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FoodBotRLRequestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRLResponse': grpc.unary_unary_rpc_method_handler(
          servicer.GetRLResponse,
          request_deserializer=FoodBotRLAgent__pb2.EnvornmentInfomration.FromString,
          response_serializer=FoodBotRLAgent__pb2.Policy.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FoodBot.FoodBotRLRequest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
