# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import FoodBot_pb2 as FoodBot__pb2


class FoodBotRequestStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetResponse = channel.unary_unary(
        '/FoodBot.FoodBotRequest/GetResponse',
        request_serializer=FoodBot__pb2.Sentence.SerializeToString,
        response_deserializer=FoodBot__pb2.outSentence.FromString,
        )


class FoodBotRequestServicer(object):

  def GetResponse(self, request, context):
    """Input NLG
    Output NLG 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FoodBotRequestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetResponse': grpc.unary_unary_rpc_method_handler(
          servicer.GetResponse,
          request_deserializer=FoodBot__pb2.Sentence.FromString,
          response_serializer=FoodBot__pb2.outSentence.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FoodBot.FoodBotRequest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
