# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FoodBotSim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FoodBotSim.proto',
  package='FoodBotSim',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x46oodBotSim.proto\x12\nFoodBotSim\"\x1c\n\x08Sentence\x12\x10\n\x08response\x18\x01 \x01(\t2S\n\x11\x46oodBotSimRequest\x12>\n\x0eGetSimResponse\x12\x14.FoodBotSim.Sentence\x1a\x14.FoodBotSim.Sentence\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='FoodBotSim.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='FoodBotSim.Sentence.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'FoodBotSim_pb2'
  # @@protoc_insertion_point(class_scope:FoodBotSim.Sentence)
  ))
_sym_db.RegisterMessage(Sentence)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class FoodBotSimRequestStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetSimResponse = channel.unary_unary(
          '/FoodBotSim.FoodBotSimRequest/GetSimResponse',
          request_serializer=Sentence.SerializeToString,
          response_deserializer=Sentence.FromString,
          )


  class FoodBotSimRequestServicer(object):

    def GetSimResponse(self, request, context):
      """Input NLG
      Output NLG 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_FoodBotSimRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetSimResponse': grpc.unary_unary_rpc_method_handler(
            servicer.GetSimResponse,
            request_deserializer=Sentence.FromString,
            response_serializer=Sentence.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'FoodBotSim.FoodBotSimRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaFoodBotSimRequestServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetSimResponse(self, request, context):
      """Input NLG
      Output NLG 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaFoodBotSimRequestStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetSimResponse(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Input NLG
      Output NLG 
      """
      raise NotImplementedError()
    GetSimResponse.future = None


  def beta_create_FoodBotSimRequest_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('FoodBotSim.FoodBotSimRequest', 'GetSimResponse'): Sentence.FromString,
    }
    response_serializers = {
      ('FoodBotSim.FoodBotSimRequest', 'GetSimResponse'): Sentence.SerializeToString,
    }
    method_implementations = {
      ('FoodBotSim.FoodBotSimRequest', 'GetSimResponse'): face_utilities.unary_unary_inline(servicer.GetSimResponse),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_FoodBotSimRequest_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('FoodBotSim.FoodBotSimRequest', 'GetSimResponse'): Sentence.SerializeToString,
    }
    response_deserializers = {
      ('FoodBotSim.FoodBotSimRequest', 'GetSimResponse'): Sentence.FromString,
    }
    cardinalities = {
      'GetSimResponse': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'FoodBotSim.FoodBotSimRequest', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
